- hosts: dev
    become: yes
    tasks:
      - name: install lamp stack

        apt:
          pkg:
            - apache2
            - mysql-server
            - php
            - php-mysql
          state: latest

        notify:
          - start apache
          - start mysql-server

    handlers:
      - name: start apache
        service:
          name: apache2
          state: started
          enabled: yes

      - name: start mysql-server
        service:
          name: mysql
          state: started
          enabled: yes
