---
- hosts: DEV
  gather_facts: yes
  become: true
  tasks:
    - name: "install apache2"
    yum:
      name: apache
      state: latest
    -name: "starting service"
    service: name=http state=started
    apt:
      pkg:
        - php
        - mysql
        - php-mysql
      state: latest